### ISSUE TITLE
Links to FAQ articles from CWA app no longer work

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-website#2577]
## Where to find the issue

- https://www.coronawarn.app/en/faq/
- https://www.coronawarn.app/de/faq/

## Describe the issue

A regression has been introduced with the new FAQ layout.

FAQ articles accessed from links within the CWA Android app no longer show the FAQ article.

## Steps to reproduce

Device: Pixel 3a Emulator
Android version: API 31 / Android 12
CWA Version: 2.19.2
Default apps: Browser app: Chrome

1. Open CWA
2. Scroll down to "7-Day Incidence" statistics tile
3. Tap "i" icon
4. In "Key Figures" / "Explanation of Statistics" scroll down to "You'll find answers to frequently asked questions on our FAQ page:

![Key Figures](https://user-images.githubusercontent.com/66998419/160158723-4613eaba-6b7e-4f3a-b386-03cb51e390e0.jpg)

5. Tap on FAQ in the above sentence
6. The address bar shows "coronawarn.app/en/faq/results/#further_details" however the browser is scrolled down to the footer

![FAQ in browser](https://user-images.githubusercontent.com/66998419/160158749-6b71de30-e078-4d0a-9576-e44aa99f1a3c.jpg)

7. Scroll back up and note that the requested article is not visible

This is reproducible also with other FAQ links from the app.

It is reproducible with browsers:
- Google Chrome
- Mozilla Firefox
- Samsung Internet

## Additional information

The expected result of tapping a link to an FAQ article in the CWA is that the article should be displayed in a browser window on the mobile device, expanded and scrollable so that it is immediately available for reading.

Different links produce different error conditions different from the expected result:

1. Footer shown
2. Article not expanded (see also https://github.com/corona-warn-app/cwa-website/issues/2584)
3. No article shown (only the section headers are shown)

The following table contains a list of anchors which are always accessible in CWA Android. There are other links which are only shown based on certain conditions like red card or in combination with an error.

Link | Access through | Result
-- | -- | --
[#where_can_i_get_tested](https://www.coronawarn.app/en/faq/#where_can_i_get_tested) | Manage Your Tests > Find Testing Center | Article not expanded
[#notification_settings](https://www.coronawarn.app/en/faq/#notification_settings) | Settings > Notifications | Footer shown / article not expanded
[#eu_dcc](https://www.coronawarn.app/en/faq/#eu_dcc) | Scan a certificate which is already stored | ~~No article shown~~ Certificate section shown
[#eu_dcc_check](https://www.coronawarn.app/en/faq/#eu_dcc_check) | 	Certificates > "i" with stored certificate | Article not expanded
[#error_log](https://www.coronawarn.app/en/faq/#error_log) | App Information > Error Reports | Article not expanded
[#further_details](https://www.coronawarn.app/en/faq/#further_details) | Statistic tile > "I" | Footer shown / article not expanded
[#interoperability_countries](https://www.coronawarn.app/en/faq/results/#interoperability_countries) | App Information > Data Privacy, Section 7 (end) | Article not expanded
[#android_location](https://www.coronawarn.app/en/faq/#android_location) | Android 6 - 10, disable location > LOCATION SERVICES DEACTIVATED | Article not expanded

The issue is also reproducible by using Google Chrome Desktop or Mozilla Firefox. View this page in the browser. Minimize the browser width and click each of the above links.

---
Internal Tracking ID: EXPOSUREAPP-12448

**Comment by Ein-Tim** [comment]
Confirm same issue for iOS:

<img src="https://user-images.githubusercontent.com/67682506/160162361-a8bf452d-2b59-45a4-aec9-6750aa2c795d.png" width="300">

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Thank you very much for checking on iOS as well! I am finding even more problems as I start using the new FAQ!

**Comment by Ein-Tim** [comment]
> I am finding even more problems as I start using the new FAQ!

So do I, I'm currently checking whether other links also cause problems (e.g. if I shared them on Twitter).

**Comment by Ein-Tim** [comment]
I identified another problem: https://github.com/corona-warn-app/cwa-website/issues/2582

**Comment by Crystalskulls** [comment]
This seems to be a CSS Bug. I can reproduce the error with an iPhone XR, but with an iPad Air all FAQ entries in this section are displayed and so the link brings me to the expected anchor.

So far i was not able to find the cause. Maybe its a @media rule problem, but my CSS is rusty, so i'm not sure.

**Comment by MikeMcC399** [comment]
@Crystalskulls 

It's linked to the width of the browser window. It fails in narrow browsers windows.

On an Android device if I turn the device on its side (so it's in landscape orientation) before tapping on the FAQ link, then the FAQ article appears correctly.

- In the meantime I've logged #2579 and #2580 which may be related.

**Comment by MikeMcC399** [comment]
## Additional information

The expected result of tapping a link to an FAQ article in the CWA is that the article should be displayed in a browser window on the mobile device, expanded and scrollable so that it is immediately available for reading.

Different links produce different error conditions different from the expected result:

1. Footer shown
2. Article not expanded (see also https://github.com/corona-warn-app/cwa-website/issues/2584)
3. No article shown (only the section headers are shown)

The following table contains a list of anchors which are always accessible in CWA Android. There are other links which are only shown based on certain conditions like red card or in combination with an error. (These are not listed here.)

Link | Access through | Result
-- | -- | --
[#where_can_i_get_tested](https://www.coronawarn.app/en/faq/#where_can_i_get_tested) | Manage Your Tests > Find Testing Center | Article not expanded
[#notification_settings](https://www.coronawarn.app/en/faq/#notification_settings) | Settings > Notifications | Footer shown
[#eu_dcc](https://www.coronawarn.app/en/faq/#eu_dcc) | Scan a certificate which is already stored | No article shown
[#eu_dcc_check](https://www.coronawarn.app/en/faq/#eu_dcc_check) | 	Certificates > "i" with stored certificate | Article not expanded
[#error_log](https://www.coronawarn.app/en/faq/#error_log) | App Information > Error Reports | Article not expanded
[#further_details](https://www.coronawarn.app/en/faq/#further_details) | Statistic tile > "I" | Footer shown
[#interoperability_countries](https://www.coronawarn.app/en/faq/results/#interoperability_countries) | App Information > Data Privacy, Section 7 (end) | Article not expanded
[#android_location](https://www.coronawarn.app/en/faq/#android_location) | Android 6 - 10, disable location > LOCATION SERVICES DEACTIVATED | Article not expanded

**Comment by MikeMcC399** [comment]
- See also enhancement request https://github.com/corona-warn-app/cwa-website/issues/2585.

**Comment by Ein-Tim** [comment]
I wonder if it would make sense to revert the FAQ redesign until these problems are addressed. I'm uncertain if a step that drastically needs to be taken, but I would say yes as nearly all links from the CWA app itself to the FAQs are broken. 

Any options on this?

**Comment by MikeMcC399** [comment]
@Ein-Tim 
> I wonder if it would make sense to revert the FAQ redesign until these problems are addressed.

I think it is a significant problem for the app. 

Whether the PR should be reverted depends on how long it is expected to take to fix it. It may be a simple fix. We don't know until the web developers take a look at it.

**Comment by Ein-Tim** [comment]
More bugs spotted: 
- #2591
- #2592
- #2593

If the team does not resolve most of the issues in the next week, I suggest to revert to the first version of the FAQs.

**Comment by MikeMcC399** [comment]
- The missing [#eu_dcc](https://www.coronawarn.app/en/faq/#eu_dcc) on the website is also listed in https://github.com/corona-warn-app/cwa-website/issues/2582.

**Comment by svengabr** [comment]
Thanks for your input, the developers will start working on the faq issues starting today.

Internal Tracking ID: EXPOSUREAPP-12448

**Comment by MikeMcC399** [comment]
- [#eu_dcc](https://www.coronawarn.app/en/faq/#eu_dcc) is fixed through PR https://github.com/corona-warn-app/cwa-website/pull/2598.

**Comment by MikeMcC399** [comment]
- I'm not seeing the problem with only the footer being displayed any more.
- The remaining problem seems to be only that the articles are not opened expanded and ready for reading.

**Comment by svengabr** [comment]
@MikeMcC399 Articles not opened/expanded was a CSP issue that was fixed with a recent PR https://github.com/corona-warn-app/cwa-website/pull/2606. Should be working now.

**Comment by MikeMcC399** [comment]
@svengabr 

> Articles not opened/expanded was a CSP issue that was fixed with a recent PR https://github.com/corona-warn-app/cwa-website/pull/2606. Should be working now.

This isn't fixed for a mobile device which is what this issue is all about.

Open https://www.coronawarn.app/en/faq/#where_can_i_get_tested in Google Chrome Desktop in full-screen, then the article is displayed.

Open Google Chrome Desktop, Press F12 and select mobile device then open  https://www.coronawarn.app/en/faq/#where_can_i_get_tested shows "Where can I get tested?" not expanded:

![image](https://user-images.githubusercontent.com/66998419/160586554-fdaa9fbe-715a-493e-acd1-9186fdf15136.png)

I confirmed also using the Corona-Warn-App (2.19.2) to access the article and it is not opened there either.
